### ISSUE TITLE
latest commit App shows error while building to Run

### ISSUE THREAD

**Issue by shekooogames** [IBM-MIL/CognitiveConcierge#23]
CognitiveConcierge-iOS/CognitiveConcierge/MessagesViewController.swift:21:8: Missing required modules: 'Ogg', 'Opus'

**Comment by bvennam** [comment]
@upwardstudios Just wanted to give you an update that we were able to recreate & are looking into it.  Does the app ultimately run for you?  If not, you can try re-running the carthage update command, but with these options:

carthage update --platform iOS --no-use-binaries

This will take a bit longer, since you're not using the pre-built binaries.

**Comment by shekooogames** [comment]
i just tried with that option and it seems to work !

**Comment by stevemar** [comment]
closing since `carthage update --platform iOS --no-use-binaries` resolved the issue
