### ISSUE TITLE
is this project built with linux?

### ISSUE THREAD

**Issue by VicoErv** [IBM-MIL/CognitiveConcierge#40]

**Comment by dolph** [comment]
I assume this can be closed since it's not actually an issue, but to answer the question: I believe the iOS bits require XCode to build (and thus depends on OS X), but the rest of it should be platform independent. [IBM Cloud Tools for Swift](http://cloudtools.bluemix.net/) is specifically written for OS X as well, but there's some non-OS X docs there that should come in handy in lieu of OS X.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:47619 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eWprO-0039Ri-Eu
	for greg@biomassiv.es; Wed, 03 Jan 2018 14:42:02 -0600
Date: Wed, 03 Jan 2018 12:41:23 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1515012083;
	bh=iPb/yCZzlWlrgKsiWcahUIL0QZyCH9iI/zv9SPeMZMY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=fVUCgiVnHdD72ABJF3qVmgrUZ0DK2rAAMZ8I9fADEeOQixDnpTD34TIdNZDfjxdXo
	 wr6eaTzPUXmaDcL6b6isgEvt05Simv77R/fPnkIKNb+N5zyPncKxNmXTo0TVSvSxa8
	 sWonNnDOmE0wQlFnCZOAFaz8aHXvQar56e8Y99/Q=
